# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
sudo: required
dist: trusty

r_github_packages:
  - jimhester/covr

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - libfftw3-dev
      - cargo
