# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
sudo: required

r_binary_packages:
  - devtools
  - ggplot2
  - phangorn
  - ape
  - tidyr
  - tibble
  - reshape2
  - methods
  - testthat
  - knitr
  - rmarkdown

r_github_packages:
  - jimhester/covr

before_install:
  - tlmgr install fullpage

after_success:
  - Rscript -e 'covr::coveralls()'
  
notifications:
  email:
    on_success: change
    on_failure: always